export const selectorsList = {
  ID_PAGE: "#selectedinsurance",
  MAKE: "#make",
  ENGINE: "#engineperformance",
  DATE: "#dateofmanufacture",
  NUMBER_OF_SEATS: "#numberofseats",
  RIGHT_HAND: Math.random() < 0.5 ? "#righthanddriveyes" : "#righthanddriveno",
  FUEL_TYPE: "#fuel",
  LIST_PRICE: "#listprice",
  LICENCE_PLATE: "#licenseplatenumber",
  ANNUAL_MILEAGE: "#annualmileage",
  BTN_NEXT: "#nextenterinsurantdata",
  ABA_VEHICLE_DATA: ".idealsteps-step-active, a[name= 'Enter Vehicle Data']",
  COUNTER: "span.counter.zero",
  MANDATORY_FORM: ".invalid",
};
